# Importing numpy library

In [1]:
import numpy as np

In [13]:
#1D Array
arr1=np.array([1,2,3,4,5],dtype=int)
print(arr1)
arr2=np.array([1,2,3,4,5],dtype=float)
print(arr2)
arr3=np.array([1,2,3,4,5],dtype=complex)
print(arr3)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


# Array Slicing

In [19]:
print(arr1[0:])
print(arr1[1:])
print(arr1[2:])
print(arr1[2:5])
print(arr1[1:5])

[1 2 3 4 5]
[2 3 4 5]
[3 4 5]
[3 4 5]
[2 3 4 5]


# MAtrix Multiplicaction

In [41]:
#2D Array
Matrix2=np.array([[1,2,3],[4,5,6],[7,8,9]])
Matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("*"*15,end='\n')
print("Matrix1:",Matrix1)


print("*"*15)
print("Matrix2:",Matrix2)


print("*"*15)
C=A@B   # @Sign Used for Matrix mulitplication
print(c)

***************
Matrix1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
***************
Matrix2: [[1 2 3]
 [4 5 6]
 [7 8 9]]
***************
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [77]:
#Creating Dot Product of Matrix
Matrix3=np.dot(Matrix1,Matrix2)
print(Matrix3)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [78]:
#Creating Cross product Of Matrix
Matrix4=np.cross(Matrix1,Matrix2)
print(Matrix4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [85]:
#Creating Addition Of Matrix
Matrix5=Matrix1+Matrix2
print(Matrix5)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [86]:
#Creating Addition Of Matrix
Matrix6=Matrix1-Matrix2
print(Matrix5)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [87]:
#Creating Addition Of Matrix
Matrix7=Matrix1/Matrix2
print(Matrix7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [88]:
#Creating element Wise multiplication Not a Matrix Multiplication
Matrix8=Matrix1*Matrix2
print(Matrix8)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [93]:
#Creating Identity Matrix
example10=np.identity(3,dtype=int)
print(example10)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### shape : Number of rows
### order : C_contiguous or F_contiguous
### dtype : [optional, float(by Default)] Data type of returned array.

In [89]:
example0=np.array([[1,2,3],[4,5,6]])
print(example0)
print(example0.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [90]:
#Creating Empty Array
example1=np.empty(5) #deafult dtype is float
print(example1)

example2=np.empty(10,dtype=int) 
print(example2)

example3=np.empty(15,dtype=complex)
print(example3)

[1. 1. 1. 1. 1.]
[         0 1072693248          0 1072693248          0 1072693248
          0 1072693248          0 1072693248]
[8.90490836e-312+9.63428009e-322j 0.00000000e+000+0.00000000e+000j
 8.89116236e-312+5.02034658e+175j 1.20134396e-075+2.93053504e-057j
 4.55814802e-037+8.00661411e+165j 1.47763641e+248+1.16096346e-028j
 7.69165785e+218+1.35617292e+248j 2.13875455e+184+3.24791130e-057j
 1.54767492e+185+3.35098528e-033j 4.30256311e-096+6.32299154e+233j
 3.65588282e+233+1.74569531e+238j 1.11763132e+261+1.16318408e-028j
 2.24729310e+174+1.56605686e-076j 6.74204472e-067+6.37361879e-062j
 1.24689926e-047+7.72043097e+140j]


In [91]:
#Creating Zeros Matrix
example4=np.zeros(5) #deafult dtype is float
print(example4)

example5=np.zeros(10,dtype=int) 
print(example5)

example6=np.zeros(15,dtype=complex)
print(example6)

[0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [117]:
#Creating ones Matrix
example7=np.ones(5) #deafult dtype is float
print(example7)

example8=np.ones(10,dtype=int) 
print(example8)

example9=np.ones(15,dtype=complex)
print(example9)

[1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j
 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


In [118]:
#Creating full Matrix
example7=np.full(5,9) #deafult dtype is float
print(example7)

example8=np.full(10,9,dtype=int) 
print(example8)

example9=np.full(15,9,dtype=complex)
print(example9)

[9 9 9 9 9]
[9 9 9 9 9 9 9 9 9 9]
[9.+0.j 9.+0.j 9.+0.j 9.+0.j 9.+0.j 9.+0.j 9.+0.j 9.+0.j 9.+0.j 9.+0.j
 9.+0.j 9.+0.j 9.+0.j 9.+0.j 9.+0.j]


In [119]:
#reshape Fuction
example10=np.array([[3,2,1],[1,2,3]])
print(example10.shape)
example10.reshape(3,2)

(2, 3)


array([[3, 2],
       [1, 1],
       [2, 3]])

In [120]:
#Creating Series numpy
series1=np.arange(10)
print(series1)
series2=np.arange(0,10,2) #Even number
print(series2)
series3=np.arange(1,10,2) #Odd Number
print(series3)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]


In [121]:
series4=np.arange(40)
series5=series4.reshape(8,5)
print(series5)

series6=series4.reshape(5,8)
print(series6)

series7=series4.reshape(2,20)
print(series7)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]


In [122]:
series8 = np.arange(8) 
print("Original Array : \n", series8) 
  
# shape arr with 2 rows and 4 columns 
series9 = np.arange(8).reshape(2, 4) 
print("\nArray reshaped with 2 rows and 4 columns : \n", series9) 
  
# shape arr with 2 rows and 4 columns 
series10 = np.arange(8).reshape(4 ,2) 
print("\nArray reshaped with 2 rows and 4 columns : \n", series10) 
  
# Constructs 3D arr 
series11 = np.arange(8).reshape(2, 2, 2) 
print("\nOriginal Array reshaped to 3D : \n", series11)

Original Array : 
 [0 1 2 3 4 5 6 7]

Array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

Array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original Array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [128]:
#linspace fuction in numpy
X=np.linspace(1,10,6)
print(X)
#formula_for_step
#step_value=stop-start/num-1

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [135]:
#endpoint consideration
Y=np.linspace(1,10,6,endpoint=False)
print(Y)

[1.  2.5 4.  5.5 7.  8.5]


In [138]:
#to return the retstep(returen stepvalue) default is False
Z=np.linspace(1,10,6,retstep=True)
print(Z)

(array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ]), 1.8)


In [132]:
#np.asarray function

#tuple to Array
tuple1=(1,2,3,4)
array1=np.asarray(tuple1)
print(array1)

#list to Array
list1=[9,8,7,6]
array2=np.asarray(list1)
print(array2)


[1 2 3 4]
[9 8 7 6]


In [177]:
str1="Welcome_Vsquare_System"
print(str1)
s=slice(1,4,2) #slice(start,stop,step)
print(str1[s])
s=slice(0,len(str1),1)
print(str1[s])
s=slice(0,len(str1),2)
print(str1[s])
s=slice(0,len(str1),3)
print(str1[s])

Welcome_Vsquare_System
ec
Welcome_Vsquare_System
WloeVqaeSse
Wcesa_sm


In [183]:
print(Matrix1)
print(" \n",Matrix1[...,0]) #0st Colume
print(" \n",Matrix1[...,1]) #1 column
print(" \n",Matrix1[...,2]) #2 column
print(" \n",Matrix1[0,...]) #0 row
print(" \n",Matrix1[1,...]) #1 row
print(" \n",Matrix1[2,...]) #2 row

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
 [1 4 7]
 
 [2 5 8]
 
 [3 6 9]
 
 [1 2 3]
 
 [4 5 6]
 
 [7 8 9]


# Broadcasting in numpy

In [194]:
#Brodcasting (Mismatch Matrix multiplication)
a1=np.array([[1,2,3],[4,5,6],[7,8,9]]) #size Of Matrix
print(a1)
print(a1.shape)
a2=np.array([9,8,1]) #size of Matrix
print(a2)
print(a2.shape)
print(a1*a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[9 8 1]
(3,)
[[ 9 16  3]
 [36 40  6]
 [63 64  9]]
